build:
  image: golang:1.5
  commands:
    - make deps
    - make build
    - make test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-heroku
    when:
      branch: master

plugin:
  name: Heroku
  desc: Deploys or updates a project on Heroku
  type: deploy
  image: plugins/drone-heroku
  labels:
    - heroku
