pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-heroku
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Heroku
  desc: Deploy or update a project on Heroku
  type: deploy
  image: plugins/drone-heroku
  labels:
    - heroku
